### ISSUE TITLE
error: namespace "thor" has no member "InstanceSegmentation"

### ISSUE THREAD

**Issue by Crystalxd** [jinfagang/thor#11]
When I make the onnx_deploy/trt_onnx, I got these error:

/usr/local/cuda/bin/nvcc /home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.cu -c -o /home/dl/projects/onnx_deploy/trt_onnx/build/CMakeFiles/trt_engine_lib.dir/include/plugins/kernels/./trt_engine_lib_generated_mask_select.cu.o -ccbin /usr/bin/c++ -m64 -Dtrt_engine_lib_EXPORTS -Xcompiler ,\"-std=c++14\",\"-Wall\",\"-Wno-deprecated-declarations\",\"-Wno-unused-function\",\"-Wno-unused-but-set-variable\",\"-fPIC\",\"-g\" -Xcompiler -fPIC --expt-extended-lambda -DNVCC -I/usr/local/cuda/include/ -I/home/dl/cub/cub -I/home/dl/projects/onnx_deploy/trt_onnx/include -I/home/dl/projects/onnx_deploy/trt_onnx/include/plugins -I/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels -I/usr/local/cuda/include -I/home/dl/projects/TensorRT-7.1.3.4/include -I/usr/local/include/opencv4
/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.h(36): error: namespace "thor" has no member "InstanceSegmentation"

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.h(50): error: identifier "InstanceSegmentation" is undefined

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.cu(44): error: identifier "InstanceSegmentation" is undefined

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.cu(45): error: identifier "insg" is undefined

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.cu(45): error: expected an expression

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.cu(54): error: identifier "InstanceSegmentation" is undefined

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.cu(89): error: identifier "InstanceSegmentation" is undefined

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.cu(89): error: identifier "insts" is undefined

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.cu(101): error: identifier "InstanceSegmentation" is undefined

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.h(36): error: namespace "thor" has no member "InstanceSegmentation"

/home/dl/projects/onnx_deploy/trt_onnx/include/plugins/kernels/mask_select.h(50): error: identifier "InstanceSegmentation" is undefined
....

How to solve it?

**Comment by lucasjinreal** [comment]
@Crystalxd  thor default installation will generate protobuf head files in `build_simple.sh`, this is done inside cmake.

If you haven't generated one, reason could be:

1) You have errors in `mkdir build && cmake .. ` and you missed it;
2) You don't have protoc and libprotobuf-dev installed.

Pls install related dependencies first, thor gonna need protobuf since it depends on it to do several visualization function.

**Comment by Crystalxd** [comment]
OK. Thx
I used the latest thor with c++14 to solve this issue. I close it.
