### ISSUE TITLE
No training process supported?

### ISSUE THREAD

**Issue by MirrorYuChen** [jinfagang/thor#3]

**Comment by lucasjinreal** [comment]
thor is not for training purpose either inference, it's just a helper lib.

**Comment by MirrorYuChen** [comment]
ok，Thanks a lot！

**Comment by lucasjinreal** [comment]
For training and model deployment you can reference our model hub: http://manaai.cn

**Comment by MirrorYuChen** [comment]
已经办了会员，哈哈哈哈~
