### ISSUE TITLE
protobuff使用什么版本

### ISSUE THREAD

**Issue by zhb0920** [jinfagang/thor#9]
mkdir: cannot create directory ‘build’: File exists
-- Build with OpenCV
--     OpenCV version: 2.4.9.1
--     OpenCV include path: /usr/include/opencv/usr/include
CMake Warning at /usr/local/share/cmake-3.14/Modules/FindProtobuf.cmake:494 (message):
  Protobuf compiler version doesn't match library version 2.6.1
Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)

--  protoc:  libprotobuf: 2.6.1
-- /home/zhb/software/thor/include/proto/det.proto/home/zhb/software/thor/include/proto/insg.proto
-- /home/zhb/software/thor/include/proto/det.pb.h
-- /home/zhb/software/thor/include/proto/det.pb.h/home/zhb/software/thor/include/proto/insg.pb.h
-- OpenCV: ON
-- Eigen: ON
-- Protobuf: ON
-- CV_EX: ON
-- CURL: ON
-- BUILD_STATIC: OFF
-- Proto headers: /home/zhb/software/thor/include/proto/det.pb.h/home/zhb/software/thor/include/proto/insg.pb.h
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhb/software/thor/build
[  4%] Building CXX object CMakeFiles/thor.dir/include/proto/insg.pb.cc.o
[  4%] Building CXX object CMakeFiles/thor.dir/include/proto/det.pb.cc.o
In file included from /home/zhb/software/thor/include/proto/det.pb.cc:4:0:
/home/zhb/software/thor/include/proto/det.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
In file included from /home/zhb/software/thor/include/proto/insg.pb.cc:4:0:
/home/zhb/software/thor/include/proto/insg.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is

**Comment by lucasjinreal** [comment]
@zhb0920 都可以，但是你电脑里面存在多个版本。试着删掉其中一个
